apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: api-gateway
  name: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: api-gateway
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: api-gateway
    spec:
      containers:
        - env:
            - name: AUTH_SERVICE_URL
              value: http://auth-service:3000
            - name: PORT
              value: "4000"
            - name: QUEST_CATALOG_SERVICE_URL
              value: http://quest-catalog-service:3001
            - name: QUEST_PROCESSING_SERVICE_URL
              value: http://quest-processing-service:3002
          image: ayounghappy/speakquest-api-gateway:latest
          name: api-gateway
          ports:
            - containerPort: 4000
              protocol: TCP
      restartPolicy: Always
