apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: quest-catalog-service
  name: quest-catalog-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: quest-catalog-service
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: quest-catalog-service
    spec:
      containers:
        - env:
            - name: AUTH_SERVICE_URL
              value: http://auth-service:3000
            - name: MONGODB_URI
              value: mongodb://mongo:27017/quest_catalog_db
          image: ayounghappy/speakquest-quest-catalog-service:latest
          name: quest-catalog-service
          ports:
            - containerPort: 3001
              protocol: TCP
      restartPolicy: Always
