apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: quest-catalog-service
  name: quest-catalog-service
spec:
  type: NodePort  # NodePort로 설정
  ports:
    - port: 3001
      targetPort: 3001
      nodePort: 32001  # 외부에서 접근할 때 사용할 포트
  selector:
    io.kompose.service: quest-catalog-service